import "../styles/globals.css";
import { Inter } from "next/font/google";

import AuthProvider from "./components/Next-Auth";
const inter = Inter({ subsets: ["latin"] });

import KakaoLoginButton from "./components/kakaoLoginButton";
import Navbar from "./components/Navbar/Navbar";
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// ==== icon: fontawesome ====
// import { config } from "@fortawesome/fontawesome-svg-core";
// import "@fortawesome/fontawesome-svg-core/styles.css";
// config.autoAddCss = false;

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthProvider>
                    {children}
                    <Navbar />
                </AuthProvider>
            </body>
        </html>
    );
}
